image: insurgotech/heads-ci:latest

stages:
  - build

build:
  stage: build
  cache:
        paths:
            - ./
  cache:
    untracked: true
        paths:
            - ./git
  script:
    - make BOARD=x230-flash
    - make BOARD=x230
  artifacts:
    paths:
      - ./build/x230-flash/x230-flash.rom
      - ./build/x230/coreboot.rom
