#image: insurgotech/fedora-29_heads-ci
image: fedora:29

stages:
  - build

build:
  stage: build
  retry: 2
  cache:
    paths:
      - ./
    key: "$CI_COMMIT_REF_SLUG"
  script:
    - dnf install -y @development-tools	gcc-c++ gcc-gnat zlib-devel perl-Digest-MD5 perl-Digest-SHA	uuid-devel pcsc-tools qemu ncurses-devel lbzip2	libuuid-devel lzma	elfutils-libelf-devel	bc bzip2 bison flex git	gnupg	iasl m4	nasm patch	python wget libusb-devel cmake pv	bsdiff autoconf
    - git fetch origin 
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    - make BOARD=x230-libremkey
    - echo "x230 hashes:"
    - cat ./build/x230-libremkey/hashes.txt
  artifacts:
    paths:
      - ./build/x230-libremkey/coreboot.rom
      - ./build/x230-libremkey/hashes.txt
