#image: insurgotech/fedora-29_heads-ci
image: fedora:29

stages:
  - build

build:
  stage: build
  retry: 2
  cache:
    paths:
      - ./
    key: "$CI_COMMIT_REF_SLUG"
  script:
    - dnf install -y @development-tools gcc-c++ gcc-gnat zlib-devel perl-Digest-MD5 perl-Digest-SHA uuid-devel pcsc-tools ncurses-devel lbzip2 libuuid-devel lzma elfutils-libelf-devel bc bzip2 bison flex git gnupg iasl m4 nasm patch python wget libusb-devel cmake automake pv bsdiff autoconf libtool expat-devel boost-devel libaio-devel cpio diceware
    - git fetch origin 
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    - rm -rf ./build/x230-libremkey/*
    - rm -rf ./install/*
    - make BOARD=x230-libremkey || (find ./build/log/ -cmin 1|xargs tail; exit 1)
    - echo "x230 hashes:"
    - cat ./build/x230-libremkey/hashes.txt
  artifacts:
    paths:
      - ./build/x230-libremkey/coreboot.rom
      - ./build/x230-libremkey/hashes.txt
