image: insurgotech/fedora-29_heads-ci

stages:
  - build

build:
  stage: build
  retry: 2
  cache:
    paths:
      - ./
    key: "$CI_COMMIT_REF_SLUG"
  script:
    - git fetch origin 
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    - make BOARD=x230-flash-libremkey V=1
    - echo "x230-flash hashes:"
    - cat ./build/x230-flash-libremkey/hashes.txt
  artifacts:
    paths:
      - ./build/x230-flash-libremkey/x230-flash-libremkey.rom
      - ./build/x230-flash-libremkey/hashes.txt
