version: 2
jobs:
  build:
    docker:
      - image: fedora:30
    steps:
      - run:
          name: Install dependencies
          command: |
            dnf update
            dnf install -y @development-tools \
              gcc-c++ \
              gcc-gnat \
              zlib-devel \
              perl-Digest-MD5 \
              perl-Digest-SHA \
              uuid-devel \
              pcsc-tools \
              ncurses-devel \
              lbzip2 \
              libuuid-devel \
              lzma \
              elfutils-libelf-devel \
              bc \
              bzip2 \
              bison \
              flex \
              git \
              gnupg \
              iasl \
              m4 \
              nasm \
              patch \
              python \
              wget \
              libusb-devel \
              cmake \
              automake \
              pv \
              bsdiff \
              autoconf \
              libtool \
              expat-devel \
              boost-devel \
              libaio-devel \
              cpio \
              diceware \

      - checkout

      - run:
          name: x230-libremkey
          command: |
                make \
                V=1 \
                BOARD=x230-libremkey \

      - store-artifacts:
          path: build/x230-libremkey/coreboot.rom
      - store-artifacts:
          path: build/x230-libremkey/x230-libremkey-bottom.rom
      - store-artifacts:
          path: build/x230-libremkey/x230-libremkey-top.rom	
      - store-artifacts:
          path: build/x230-libremkey/hashes.txt

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
