version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y build-essential zlib1g-dev uuid-dev libdigest-sha-perl libelf-dev bc bzip2 bison flex git gnupg iasl m4 nasm patch python wget gnat cpio ccache pkg-config cmake libusb-1.0-0-dev autoconf 
      - checkout

      - run:
          name: x230-libremkey
          command: |
                make \
                V=1 \
                BOARD=x230-libremkey
          no_output_timeout: 3h
      - store-artifacts:
          path: build/x230-libremkey/coreboot.rom
      - store-artifacts:
          path: build/x230-libremkey/hashes.txt


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
